apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydealership
spec:
  selector:
    matchLabels:
      app: mydealership
  replicas: 1
  template:
    metadata:
      labels:
        app: mydealership
    spec:
      containers:
      - name: mydealership
        image: alkan369/car-dealership-image:ac968cb48101c4b49c38870232d86c3028b649ea
        ports:
        - containerPort: 8080
